/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication8.form;

import javaapplication8.dao.NhanVienDao;
import javaapplication8.until.CurrentUser;
import javax.swing.JOptionPane;

/**
 *
 * @author dungc
 */
public class Form_DoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form Form_DoiMatKhau
     */
    String tenDN = CurrentUser.get().getTenDN();

    public Form_DoiMatKhau() {
        initComponents();
        txt_tendn.setText(tenDN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_tendn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_tbmkcu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_tbmkmoi = new javax.swing.JLabel();
        lbl_tbnhaplaimkmoi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_mkcu = new javax.swing.JPasswordField();
        txt_mkmoi = new javax.swing.JPasswordField();
        txt_nhaplaimkmoi = new javax.swing.JPasswordField();
        btn_doimk = new javax.swing.JButton();
        chk_hienmk = new javax.swing.JCheckBox();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication8/icon/Made with insMind-result_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Tên Đăng Nhập");

        txt_tendn.setEditable(false);
        txt_tendn.setBackground(new java.awt.Color(204, 204, 204));
        txt_tendn.setText("###");

        jLabel4.setText("Mật Khẩu Hiện Tại");

        lbl_tbmkcu.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setText("Mật Khẩu Mới");

        lbl_tbmkmoi.setForeground(new java.awt.Color(255, 0, 0));

        lbl_tbnhaplaimkmoi.setForeground(new java.awt.Color(255, 0, 0));

        jLabel9.setText("Nhập Lại Mật Khẩu Mới");

        txt_mkcu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mkcuFocusGained(evt);
            }
        });

        txt_mkmoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_mkmoiFocusGained(evt);
            }
        });

        txt_nhaplaimkmoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nhaplaimkmoiFocusGained(evt);
            }
        });
        txt_nhaplaimkmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhaplaimkmoiActionPerformed(evt);
            }
        });

        btn_doimk.setBackground(new java.awt.Color(255, 255, 0));
        btn_doimk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_doimk.setForeground(new java.awt.Color(255, 51, 51));
        btn_doimk.setText("ĐỔI MẬT KHẨU");
        btn_doimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimkActionPerformed(evt);
            }
        });

        chk_hienmk.setText("Hiện Mật Khẩu");
        chk_hienmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_hienmkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nhaplaimkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_mkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mkcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tbmkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tbmkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(txt_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_hienmk)
                                    .addComponent(lbl_tbnhaplaimkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btn_doimk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_mkcu, txt_mkmoi, txt_nhaplaimkmoi, txt_tendn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_mkcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tbmkcu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_mkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tbmkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_nhaplaimkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tbnhaplaimkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_hienmk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_doimk)
                .addGap(28, 28, 28))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_mkcu, txt_mkmoi, txt_nhaplaimkmoi, txt_tendn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nhaplaimkmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhaplaimkmoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhaplaimkmoiActionPerformed

    private void btn_doimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimkActionPerformed
        String maNV = CurrentUser.getMaNV();
        String oldPass = new String(txt_mkcu.getPassword());
        String newPass = new String(txt_mkmoi.getPassword());
        String confirmNewPass = new String(txt_nhaplaimkmoi.getPassword());

        // Reset thông báo lỗi
        lbl_tbmkcu.setText("");
        lbl_tbmkmoi.setText("");
        lbl_tbnhaplaimkmoi.setText("");

        if (oldPass.isEmpty()) {
            lbl_tbmkcu.setText("Vui lòng nhập mật khẩu cũ!");
            return;
        }

        if (newPass.isEmpty()) {
            lbl_tbmkmoi.setText("Vui lòng nhập mật khẩu mới!");
            return;
        }

        if (confirmNewPass.isEmpty()) {
            lbl_tbnhaplaimkmoi.setText("Vui lòng nhập lại mật khẩu mới!");
            return;
        }

        NhanVienDao dao = new NhanVienDao();

        if (!dao.checkOldPassword(maNV, oldPass)) {
            lbl_tbmkcu.setText("Mật khẩu cũ không đúng!");
            return;
        }

        if (oldPass.equals(newPass)) {
            lbl_tbmkmoi.setText("Mật khẩu mới phải khác mật khẩu cũ!");
            return;
        }

        if (!newPass.equals(confirmNewPass)) {
            lbl_tbnhaplaimkmoi.setText("Nhập lại mật khẩu mới không khớp!");
            return;
        }

        int luachon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đổi mật khẩu không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (luachon == JOptionPane.YES_OPTION) {
            boolean success = dao.capNhatMatKhauForm(maNV, newPass);
            if (success) {
                JOptionPane.showMessageDialog(this, "✅ Đổi mật khẩu thành công!");
                // Optional: clear input
                txt_mkcu.setText("");
                txt_mkmoi.setText("");
                txt_nhaplaimkmoi.setText("");
                lbl_tbmkcu.setText("");
                lbl_tbmkmoi.setText("");
                lbl_tbnhaplaimkmoi.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thất bại. Vui lòng kiểm tra lại!");
            }
        }

    }//GEN-LAST:event_btn_doimkActionPerformed

    private void chk_hienmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_hienmkActionPerformed
        if (chk_hienmk.isSelected()) {
            // Hiển thị mật khẩu
            txt_mkcu.setEchoChar((char) 0);
            txt_mkmoi.setEchoChar((char) 0);
            txt_nhaplaimkmoi.setEchoChar((char) 0);
        } else {
            // Ẩn lại mật khẩu bằng ký tự mặc định
            txt_mkcu.setEchoChar('*');
            txt_mkmoi.setEchoChar('*');
            txt_nhaplaimkmoi.setEchoChar('*');
        }
    }//GEN-LAST:event_chk_hienmkActionPerformed

    private void txt_mkcuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mkcuFocusGained
        lbl_tbmkcu.setText("");
    }//GEN-LAST:event_txt_mkcuFocusGained

    private void txt_mkmoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_mkmoiFocusGained
        lbl_tbmkmoi.setText("");
    }//GEN-LAST:event_txt_mkmoiFocusGained

    private void txt_nhaplaimkmoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nhaplaimkmoiFocusGained
        lbl_tbnhaplaimkmoi.setText("");
    }//GEN-LAST:event_txt_nhaplaimkmoiFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doimk;
    private javax.swing.JCheckBox chk_hienmk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_tbmkcu;
    private javax.swing.JLabel lbl_tbmkmoi;
    private javax.swing.JLabel lbl_tbnhaplaimkmoi;
    private javax.swing.JPasswordField txt_mkcu;
    private javax.swing.JPasswordField txt_mkmoi;
    private javax.swing.JPasswordField txt_nhaplaimkmoi;
    private javax.swing.JTextField txt_tendn;
    // End of variables declaration//GEN-END:variables
}
